# Generated by Django 5.0 on 2024-01-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='titulo',
        ),
    ]
